services:
  db:
    image: postgres:16-bookworm
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: intania-oidc

  redis:
    image: redis:7.2-bookworm
    ports:
    - 6379:6379
    command: ["redis-server", "--requirepass", "123456"]
