name: Check formating

on:
  push:
    branches:
      - "main"
  pull_request: {}

jobs:
  check_format:
    name: Check Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run prettier check
        run: npx prettier . --check
